import { mkdir, copyFile } from "node:fs/promises";
import { build } from "esbuild";

await mkdir("build", { recursive: true });

await build({
  entryPoints: ["src/gas.ts"],
  bundle: true,
  outfile: "build/Code.js",
  format: "iife",
  platform: "browser",
  target: "es2020",
  banner: {
    js: "/* Generated by npm run build. Do not edit build/Code.js directly. */",
  },
});

await copyFile("appsscript.json", "build/appsscript.json");
