import { mkdir, copyFile, readFile } from "node:fs/promises";
import { build } from "esbuild";

await mkdir("build", { recursive: true });
await verifyAppsScriptManifest();

const appsScriptEntrypointFooter = `
function onOpen() {
  return globalThis.__snowGrowthSignalTracker.onOpen();
}

function runWeeklyTracker() {
  return globalThis.__snowGrowthSignalTracker.runWeeklyTracker();
}

function runWeeklyTrackerDryRun() {
  return globalThis.__snowGrowthSignalTracker.runWeeklyTrackerDryRun();
}

function runWeeklyTrackerScheduled() {
  return globalThis.__snowGrowthSignalTracker.runWeeklyTrackerScheduled();
}

function installWeeklyTrigger() {
  return globalThis.__snowGrowthSignalTracker.installWeeklyTrigger();
}
`;

await build({
  entryPoints: ["src/gas.ts"],
  bundle: true,
  outfile: "build/Code.js",
  format: "iife",
  platform: "browser",
  target: "es2020",
  banner: {
    js: "/* Generated by npm run build. Do not edit build/Code.js directly. */",
  },
  footer: {
    js: appsScriptEntrypointFooter,
  },
});

await copyFile("appsscript.json", "build/appsscript.json");

async function verifyAppsScriptManifest() {
  const manifest = JSON.parse(await readFile("appsscript.json", "utf8"));
  if (manifest.executionApi?.access !== "MYSELF") {
    throw new Error("appsscript.json executionApi.access must stay MYSELF for private workbook QA.");
  }
}
